# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
os: linux
dist: bionic
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  matrix:
    - USE_DEB=true   ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - USE_DEB=true   ROS_DISTRO="melodic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" PRERELEASE=true
    - USE_DEB=true   ROS_DISTRO="noetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="noetic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" PRERELEASE=true
    - env: ROS_DISTRO="melodic" PRERELEASE=true
    - env: ROS_DISTRO="noetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script
